[package]
name = "xcoffee"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12", features = ["tokio", "image"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["stream"] }
image = "0.24"

futures-util = "0.3.30"
bytes = "1"
